name: Build and publish release on new tag
on:
  push:
    tags:
      - '*'

jobs:
  
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          # TODO: replace username with action variable
          username: punksecurity
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
        id: version
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Run Buildx
        run: |
          docker buildx build . \
            --push \
            --progress=plain \
            --tag docker.io/punksecurity/dnsreaper:${{ steps.version.outputs.version }} \
            --tag docker.io/punksecurity/dnsreaper:latest \
            --platform linux/amd64 \
            --platform linux/arm64
